# general x.x.134.222
batch_size: 16
input_size: 512
sub_name: 'unet_dual'
backbone_type: 'unet' #
loss_fun: 'mean_absolute_error'


num_samples: 300
epochs: 300
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000

train_dataset: 'data/DUAL'
#test_dataset: './data/test_dataset'
